### ISSUE TITLE
Enable various sizes of DB

### ISSUE THREAD

**Issue by smjmoj** [ministryofjustice/hmpps-delius-core-oracledb-bootstrap#17]
Make amendments to enable bootstrapping regardless to instance type and disk type, size and quantity.
Currently T2 compatible, needs to be T3 and R5 compatible with NVME disks.

**Comment by brettminnie** [comment]
If you can do mounting to be smart regardless of disks that would be first prize

**Comment by smjmoj** [comment]
Yes achieved.
